version: "2"
services:
  webserverdev:
    environment:
      MOODLE_DOCKER_DBTYPE: sqlsrv
      MOODLE_DOCKER_DBUSER: sa
  dbdev:
    image: moodlehq/moodle-db-mssql
    environment:
        ACCEPT_EULA: "y"
        SA_PASSWORD: "m@0dl3ing"
