version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    ports:
      - "127.0.0.1:5432:5432"
