version: "2"
services:
  webserverdec:
    environment:
      MOODLE_DOCKER_PHPUNIT_EXTRAS: "true"
  memcacheddev0:
    image: memcached:1.4
  memcacheddev1:
    image: memcached:1.4
  mongodev:
    image: mongo:4.0
  redisdev:
    image: redis:3
  solrdev:
    image: solr:6.5
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test
  ldapdev:
    image: larrycai/openldap
