version: "2"
services:
  webserverdev:
    environment:
      MOODLE_DOCKER_BROWSER: chrome
  seleniumdev:
    image: "selenium/standalone-chrome${MOODLE_DOCKER_SELENIUM_SUFFIX}:3"
    volumes:
        - /dev/shm:/dev/shm
